# Site settings
baseurl = "https://live4thee.github.io/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Life as a Programmer"
theme = "cactus-plus"
paginate = 5

hasCJKLanguage = true
disqusShortname = "live4thee"

[params]
  author = "live4thee"
  description = "The Good, the Bad and the Ugly"
  bio = "`Simplicity is prerequisite for reliability.' - EWD"

  ##################################
  # The variables below are optional
  ##################################

  enableRSS = true
  enableComments = true

  # math typesetting
  math = false

  showToc = true
  showPowerBy = true
  hiddenPostSummaryInHomePage = false

  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright = ""

# Add additional social link entries underneath
[social]
  facebook = "https://www.facebook.com/live4thee"
  twitter = "https://twitter.com/live4thee"
  github = "https://github.com/live4thee"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
